Salesforce:
  Username: integration.mulesoft@skflubircation.com.emea
  Password: Dnpabst8DIAbwiGhUgT6
  SecurityToken: QmjH9bWUPd6I4uJ7nrJvQwiI8
  AuthURL: https://test.salesforce.com/services/Soap/u/58.0

http:
  port: "8081"
  
api:
  instance: "18445442"
  
salesareasapi:
  host: "salesforce-sales-area-sapi-huyoff.m3jzw3-2.deu-c1.cloudhub.io"
  port: "443"
  
accountssapi:
  host: "salesforce-accounts-sapi-huyoff.5sc6y6-2.usa-e2.cloudhub.io"
  port: "443"
  
partnerfuncsapi:
  host: "salesforce-partner-function-sapi-huyoff.m3jzw3-2.deu-c1.cloudhub.io"
  port: "443"
  
ordersapi:
  host: "salesforce-orders-sapi-huyoff.m3jzw3-2.deu-c1.cloudhub.io"
  port: "443"
  
    
productsapi:
  host: "salesforce-products-sapi-huyoff.m3jzw3-2.deu-c1.cloudhub.io"
  port: "443"
